# Generated by Django 4.1.7 on 2023-04-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_readers_remove_book_owner_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, 'So so'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], default=None, null=True),
        ),
    ]
